# src/Caching/BlogBundle/Resources/config/routing.yml
home:
    pattern: /
    defaults: { _controller: CachingBlogBundle:Home:index }
       
login:
    pattern: /login
    defaults: { _controller: CachingBlogBundle:Home:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout
    
create_entry:
    pattern: /create
    defaults: { _controller: CachingBlogBundle:Home:create }

view_route:
    pattern: /route/{id}
    defaults: { _controller: CachingBlogBundle:Home:viewRoute }

upload_photo:
    pattern: /upload-photo
    defaults: { _controller: CachingBlogBundle:Home:uploadPhoto }

building_blocks:
    pattern: /building-blocks
    defaults: { _controller: CachingBlogBundle:Home:buildingBlocks }
