# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_assetic:
    resource: .
    type:     assetic

_cachingBlogBundle:
    resource: "@CachingBlogBundle/Resources/config/routing.yml"
    prefix: /