<?php

namespace Caching\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
    public function fetchAll()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        
        $query = $qb->select('e, r')
            ->from($this->getEntityName(), 'e')
            ->leftJoin('e.Route', 'r')
            ->orderBy('e.created', 'DESC')
            ->getQuery();
        
        return $query->getResult(Query::HYDRATE_ARRAY);
    }
}