<?php

namespace Caching\BlogBundle\Repository;

use Caching\BlogBundle\Entity\Entry;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
    public function getBaseQuery()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb = $qb->select('e, r')
            ->from($this->getEntityName(), 'e')
            ->leftJoin('e.Route', 'r')
            ->where($qb->expr()->eq('e.active', Entry::ACTIVE))
            ->orderBy('e.created', 'DESC');

        return $qb;
    }

    /**
     * Get the initial number of post to load on the page
     *
     * @param $limit Number of posts
     * @return mixed
     */
    public function fetchInitial($limit)
    {
        $qb     = $this->getBaseQuery();
        $query  = $qb->getQuery();

        $query->setMaxResults($limit);

        return $query->getResult(Query::HYDRATE_OBJECT);
    }

    public function fetchNextPost($offset)
    {
        $qb     = $this->getBaseQuery();
        $query  = $qb->getQuery();

        $query->setMaxResults(1);
        $query->setFirstResult($offset);

        return $query->getSingleResult(Query::HYDRATE_OBJECT);
    }
}