<?php

namespace Caching\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteRepository extends EntityRepository
{
    public function fetchIds()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        
        $query = $qb->select('r')
                ->from($this->getEntityName(), 'r')
                ->getQuery();
        
        return $query->getResult(Query::HYDRATE_ARRAY);
    }
}